version: "3.9"
services:
    mfe-app:
        container_name: mfe-app
        image: mfe-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
        volumes:
          - ./angular-app1/dist/mfe2/:/app/static